### ISSUE TITLE
How to Scale

### ISSUE THREAD

**Issue by torosushi** [jeremyckahn/stylie#25]
Happy New Year!

RE: transform: scale(1,3); /* Standard syntax scale(x,y) */
How do I stretch the height the object from the right panel ? 
SCALE only have one input.

**Comment by jeremyckahn** [comment]
Hi @torosushi! Stylie doesn't support independent X and Y scaling, you are limited to scaling them together.  However, [Mantra](http://jeremyckahn.github.io/mantra/) does support this, and that tool has Stylie built in (hit "T" on your keyboard).

The UI for supporting that kind of individual property animation is a little bare-bones in Mantra, but it can be made to work with a little effort.

I'm closing this issue for now, but feel free to continue discussing this here or by opening a new issue on the [Mantra issue tracker](https://github.com/jeremyckahn/mantra/issues). Cheers!
