### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by hazleego** [jeremyckahn/stylie#35]
Hi, could you please guide me on how to install stylie. i get this errors

$ npm install https://github.com/jeremyckahn/stylie
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated cryptiles@0.2.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated boom@0.4.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@0.2.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@0.8.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hawk@0.13.1: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated request@2.21.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated connect@2.7.5: connect 2.x series is deprecated
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\User\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\User\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN deprecated @hapi/pinpoint@1.0.2: Moved to 'npm install @sideway/pinpoint'
npm ERR! npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm ERR! npm WARN deprecated graceful-fs@2.0.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm ERR! npm WARN deprecated cryptiles@0.2.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! npm WARN deprecated @hapi/formula@1.2.0: Moved to 'npm install @sideway/formula'
npm ERR! npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! npm WARN deprecated boom@0.4.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! npm WARN deprecated sntp@0.2.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm ERR! npm WARN deprecated mkdirp@0.3.5: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! npm WARN deprecated hoek@0.8.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! npm WARN deprecated hoek@0.9.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm ERR! npm WARN deprecated hawk@0.13.1: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm ERR! npm WARN deprecated coffee-script@1.3.3: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm ERR! npm WARN deprecated request@2.21.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! npm WARN deprecated @hapi/joi@16.1.8: Switch to 'npm install joi'
npm ERR! npm WARN deprecated connect@2.7.5: connect 2.x series is deprecated
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\node-sass
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp verb cli [
npm ERR! npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! npm ERR! gyp verb cli   'C:\\Users\\User\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-87149d77\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! npm ERR! gyp verb cli   'rebuild',
npm ERR! npm ERR! gyp verb cli   '--verbose',
npm ERR! npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! npm ERR! gyp verb cli   '--libsass_library='
npm ERR! npm ERR! gyp verb cli ]
npm ERR! npm ERR! gyp info using node-gyp@3.8.0
npm ERR! npm ERR! gyp info using node@14.16.0 | win32 | x64
npm ERR! npm ERR! gyp verb command rebuild []
npm ERR! npm ERR! gyp verb command clean []
npm ERR! npm ERR! gyp verb clean removing "build" directory
npm ERR! npm ERR! gyp verb command configure []
npm ERR! npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:13:12)
npm ERR! npm ERR! gyp verb `which` failed     at F (C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:68:19)
npm ERR! npm ERR! gyp verb `which` failed     at E (C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:80:29)
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:89:16
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\isexe\index.js:42:5
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\isexe\windows.js:36:5
npm ERR! npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
npm ERR! npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:13:12)
npm ERR! npm ERR! gyp verb `which` failed     at F (C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:68:19)
npm ERR! npm ERR! gyp verb `which` failed     at E (C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:80:29)
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\which\which.js:89:16
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\isexe\index.js:42:5
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\isexe\windows.js:36:5
npm ERR! npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
npm ERR! npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! npm ERR! gyp verb `which` failed }
npm ERR! npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! npm ERR! gyp verb `which` succeeded python C:\Users\User\AppData\Local\Programs\Python\Python39\python.EXE
npm ERR! npm ERR! gyp ERR! configure error
npm ERR! npm ERR! gyp ERR! stack Error: Command failed: C:\Users\User\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! npm ERR! gyp ERR! stack                       ^
npm ERR! npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! npm ERR! gyp ERR! stack
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:308:12)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
npm ERR! npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.19041
npm ERR! npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\User\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-clone-87149d77\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! npm ERR! gyp ERR! cwd C:\Users\User\AppData\Local\npm-cache\_cacache\tmp\git-clone-87149d77\node_modules\node-sass
npm ERR! npm ERR! gyp ERR! node -v v14.16.0
npm ERR! npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! npm ERR! gyp ERR! not ok
npm ERR! npm ERR! Build failed with error code: 1
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2021-04-06T15_54_11_951Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Local\npm-cache\_logs\2021-04-06T15_54_25_926Z-debug.log

**Comment by jeremyckahn** [comment]
Hi @hazleego, thanks for opening this issue! I'm not able to reproduce what you're seeing. I tried running `npm install @jeremyckahn/stylie` on Node 12, 14, and 15 with both macOS and Windows 10. Are you able to install under WSL or another UNIX-like environment?

Based on the error output, it seems that `node-sass` is breaking the installation (I see this frequently on a variety of projects). Can you try running `npm rebuild node-sass` and see if `npm install @jeremyckahn/stylie` works after that?

**Comment by hazleego** [comment]
Hi @jeremyckahn , thanks for the swift reply, the npm rebuild node-sass was successful however i get this when i try install 

$ npm install @jeremyckahn/stylie

up to date, audited 1169 packages in 6s

29 packages are looking for funding
  run `npm fund` for details

67 vulnerabilities (14 low, 24 moderate, 29 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

when i run npm audit i get a long log with this at the end 

67 vulnerabilities (14 low, 24 moderate, 29 high)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

....................

I tried opening from the github desktop .. could you assist with running stylie from the github desktop ?

thanks

**Comment by jeremyckahn** [comment]
It seems there may be an issue with your development environment that I'm not quite seeing from the logs you've provided, @hazleego. What's your use case for installing Stylie? Would it be easier to instead use the PWA at https://jeremyckahn.github.io/stylie/? That will work offline, in case you're just looking to use the app without an internet connection.

**Comment by hazleego** [comment]
Hi, I want to create css animations with stylie for wordpress websites. I think i did not get something right in the installation process.  Is there a plugin for stylie i can use on wordpress? What are the steps to install and get it right to start running stylie from github? Im very new to this but very interested to use stylie.. thanks

**Comment by jeremyckahn** [comment]
I'm glad to hear you're interested in the project! For your use case I don't think you need to worry about installing Stylie and that https://jeremyckahn.github.io/stylie/ should work just fine for you. Whether the app is installed or running from that URL, it works the same. Stylie just generates CSS strings that you can copy/paste into your project.

It sounds like you're looking for some deeper Wordpress integration, but Stylie doesn't provide that right now and I'm not sure of any projects that bridge that gap. Would copy/pasting the generated CSS work for your use case?

**Comment by hazleego** [comment]
Awesome, thanks, this should just work fine.. Let me look more into it.
By the way once im done with an animation, do i just copay and paste the css into the section of wordpress i want it to play, or i need to add some codes to the function on wordpress as well.

**Comment by hazleego** [comment]
Ok i got it.. very easy to use.. 

thanks

**Comment by jeremyckahn** [comment]
CSS animations play as soon as they're loaded by default, so there's no need to programatically kick them off. If you'd rather have the animation wait to play, you'll need to write some custom code to load the animation when it's needed.

Good luck! I'll close this issue for now since it seems that no code change is necessary, but feel free to leave more comments and I'll address them as I can. 🙂
